{% set version = "1.5" %}
{% set sha256 = "c2612d1a487d80fb4701b4a91ca1b8f8a695b1ae820570815e85e8c8b23f1283" %}

package:
  name: scandir
  version: {{ version }}

source:
  fn: scandir-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scandir/scandir-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install

requirements:
  host:
    - python
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  imports:
    - scandir

about:
  home: https://github.com/benhoyt/scandir
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'scandir, a better directory iterator and faster os.walk()'
  description: |
    scandir() is a directory iteration function like os.listdir(), except that 
    instead of returning a list of bare filenames, it yields DirEntry objects 
    that include file type and stat information along with the name. 
    Using scandir() increases the speed of os.walk() by 2-20 times (depending 
    on the platform and file system) by avoiding unnecessary calls to os.stat() in most cases.
  doc_url: https://docs.python.org/3.5/library/os.html#os.scandir
  dev_url: https://github.com/benhoyt/scandir
  doc_source_url: 

extra:
  recipe-maintainers:
    - kain88-de
    - dotsdl
