travis:
  secure:
    BINSTAR_TOKEN: aY/kVLErJkXXOO+C+C8wsgtbWQ80mzeiCgvcOJ1ke1oadESOgbQh5g1N59DM4xAb6pCtE1H3nGCUuE115JyxrvEmuAWiwNTZ4mxbs5ZqJWPyrBaHSHWBx5L+pgVr/gRSjd6O4vLT4TLVj3d9z3JGPPN/L5wzhEauNvCoe09POk1Rhqr/RVajruhrHTwqlZbbiGedXKND3vxMCrrqX+PEsJP4bVGs8qgmaOQ70/DRq0+iXb/u2KKQKXJfBP7VHksAiaFMUCNdN4YPNDHO0A4pcP4uWwGQV6vTh8ZeiAVLa4zCOOoG3R/xlp0l9rmQS4X/WQHEFr8VQx5jN19B1LwYBzL5QMWXTuZ+psEcfZxnmAWAqT/bTJpERIz1iYFGDUFK5s5kgCQowIHd9R0yTeVK+n1wdEA3d5wsAlsJOtnkDLxw1rFc+hDRRvddKTMPnuJfvcfraeDkT/KpQmqzoQuQlPWoQ4iGh0rCernAjRPO8+8guwu1b+gpdRqz7A8BqvxsV7uX5X1w8234I4GFo1oaH6eSwo15JwNe8iIbuPdXoP/fZY4F8POqApmJyy7gg1kwHBIPZdTC7L729Li5/zNx52RW1aHLJGuWE+9/ex0RGAxMuLI5cKibcn0jhgnMfwWF8WhFVO/S3Q1YZI6grhSmu//xRaC0xvp2vhKmGWiHgXk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
